# Force monolithic APK linking
android.experimental.privilegelinking=true
# Fix for duplicate R$id classes
android.nonTransitiveRClass=true

# Standard modern Android settings
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4g
org.gradle.parallel=true
# Disable to prevent stale property inheritance
org.gradle.configuration-cache=false
